line-length = 120

[lint]
select = [
    "ANN001", # missing-type-function-argument
    "ANN002", # missing-type-args
    "ANN003", # missing-type-kwargs
    "ANN201", # missing-return-type-undocumented-public-function
    "ANN202", # missing-return-type-private-function
    "ANN205", # missing-return-type-static-method
    "ANN206", # missing-return-type-class-method
    "ANN401", # any_type
    "I",       # isort
    "RET",    # flake8-return
    "RSE102", # Unnecessary parentheses on raised exception
    "RUF013", # no_implicit_optional 
    "T20",    # print found,
    "UP"     # pyupgrade
]

